az_rgname1           = "glps-tf-rg1"
az_location1         = "SouthIndiA"
az_rgname2           = "glps-tf-rg2"
az_location2         = "westindia"
mongodb_proj_name    = "glps_project"
bucket_name          = "uhg-s3-backend-table"
public_subnet_cidrs  = ["10.0.1.0/24", "10.0.3.0/24"]
private_subnet_cidrs = []
vpc_cidr_block       = "10.0.0.0/16"
instance_type        = "t2.medium"
ami                  = "ubuntu"
department           = "Optum health"
